name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux:
    name: Linux Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
  windows:
    name: Windows Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v3.1.2
      with:
    # Artifact name
         name: nms
    # A file, directory or wildcard pattern that describes what to upload
         path: ./target
  mac:
    name: Mac Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
